AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Spring Cloud Functions.
Resources:
  AwsLambdaSqsLocal:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: aws-lambda-sqs
      Handler: com.mj.aws.lambda.sqs.AwsLambdaSqsFunctionHandler
      Description: For AWS Sqs Queue
      Runtime: java8
      CodeUri: ./target/aws-lambda-sqs-0.0.2-SNAPSHOT-aws.jar
      MemorySize: 320
      Timeout: 120
      Environment:
        Variables:
          SPRING_PROFILES_ACTIVE: local
